snowsql -c etl_user -d I2B2_ETL_TEST <<- EOSQL
    
    CREATE OR REPLACE SCHEMA I2B2_ONT_RAW;    
    
    USE SCHEMA I2B2_ONT_RAW;

    CREATE TABLE CONCEPT_DIMENSION ( 
        CONCEPT_PATH   		VARCHAR(700) NOT NULL,
        CONCEPT_CD     		VARCHAR(50) NULL,
        NAME_CHAR      		VARCHAR(2000) NULL,
        CONCEPT_BLOB   		TEXT NULL,
        UPDATE_DATE    		TIMESTAMP NULL,
        DOWNLOAD_DATE  		TIMESTAMP NULL,
        IMPORT_DATE    		TIMESTAMP NULL,
        SOURCESYSTEM_CD		VARCHAR(50) NULL,
        UPLOAD_ID			INT NULL
	)
    ;

    CREATE TABLE TABLE_ACCESS (
        	C_TABLE_CD VARCHAR(50)	NOT NULL, 
	        C_TABLE_NAME VARCHAR(50)	NOT NULL, 
            C_PROTECTED_ACCESS CHAR(1)	NULL,
            C_HLEVEL INT				NOT NULL, 
            C_FULLNAME VARCHAR(700)	NOT NULL, 
            C_NAME VARCHAR(2000)		NOT NULL, 
            C_SYNONYM_CD CHAR(1)	NOT NULL, 
            C_VISUALATTRIBUTES CHAR(3)	NOT NULL, 
            C_TOTALNUM INT			NULL, 
            C_BASECODE VARCHAR(50)	NULL, 
            C_METADATAXML TEXT		NULL, 
            C_FACTTABLECOLUMN VARCHAR(50)	NOT NULL, 
            C_DIMTABLENAME VARCHAR(50)	NOT NULL, 
            C_COLUMNNAME VARCHAR(50)	NOT NULL, 
            C_COLUMNDATATYPE VARCHAR(50)	NOT NULL, 
            C_OPERATOR VARCHAR(10)	NOT NULL, 
            C_DIMCODE VARCHAR(700)	NOT NULL, 
            C_COMMENT TEXT	NULL, 
            C_TOOLTIP VARCHAR(900)	NULL, 
            C_ENTRY_DATE timestamp		NULL, 
            C_CHANGE_DATE timestamp	NULL, 
            C_STATUS_CD CHAR(1)		NULL,
            VALUETYPE_CD VARCHAR(50)	NULL,
            C_ONTOLOGY_PROTECTION	TEXT	NULL
    )     
    ;


    CREATE TABLE SCHEMES (
    	C_KEY VARCHAR(50)	 	NOT NULL,
	    C_NAME VARCHAR(50)		NOT NULL,
	    C_DESCRIPTION VARCHAR(100)	NULL
    ) 
    ;
EOSQL

snowsql -c etl_user -d I2B2_ETL_TEST -s I2B2_ONT_RAW -f /home/ENACT_V41_POSTGRES_I2B2_TSV/AA_CREATE_METADATA_TABLES_V41_POSTGRES.sql


