#!/bin/bash
set -e

LOCAL_STAGE="file:///home/ENACT_V41_POSTGRES_I2B2_TSV"
SNOWFLAKE_STAGE="i2b2_ont_import"
FILE_FORMAT="i2b2_ont_import"
PUT_PARAMETERS="PARALLEL=4 AUTO_COMPRESS=TRUE SOURCE_COMPRESSION=AUTO_DETECT OVERWRITE=TRUE"


# CONNECT TO SNOWFLAKE
snowsql -c etl_user -d I2B2_ETL_TEST -s I2B2_ONT_RAW  <<- EOSQL

    CREATE OR REPLACE FILE FORMAT $FILE_FORMAT
    TYPE=CSV
    FIELD_DELIMITER = '\t'
    ESCAPE=NONE
    NULL_IF = ('NULL')
    COMPRESSION=AUTO
    ESCAPE_UNENCLOSED_FIELD=NONE
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE
    SKIP_HEADER=1;

    --- CREATE STAGE AREA
    CREATE OR REPLACE STAGE $SNOWFLAKE_STAGE FILE_FORMAT = $FILE_FORMAT;

EOSQL


# CONNECT TO SNOWFLAKE
snowsql -c etl_user -d I2B2_ETL_TEST -s I2B2_ONT_RAW  <<- EOSQL

    -- PUT LOCAL FILES INTO SNOWFLAKE STAGE
    PUT $LOCAL_STAGE/* @$SNOWFLAKE_STAGE $PUT_PARAMETERS;
    
EOSQL




