--I2B2_SANDBOX_GPC

GRANT OWNERSHIP ON DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE REVOKE CURRENT GRANTS;

GRANT usage ON database I2B2_SANDBOX_GPC TO ROLE I2B2_PROD_APP_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON ALL VIEWS IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON ALL sequences IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;
GRANT ALL ON FUTURE sequences IN DATABASE I2B2_SANDBOX_GPC to role I2B2_PROD_APP_ROLE;

