CREATE OR REPLACE VIEW {target_schema}.COVID_FACT as 
SELECT * FROM {target_schema}.DIAGNOSIS_FACT 
UNION ALL
SELECT * FROM {target_schema}.PROCEDURE_FACT
UNION ALL
SELECT * FROM {target_schema}.LAB_FACT
UNION ALL 
SELECT * FROM {target_schema}.MEDICATION_FACT
UNION ALL 
SELECT * FROM {target_schema}.VISIT_FACT
UNION ALL 
SELECT * FROM {target_schema}.DEMOGRAPHIC_FACT;