USE ROLE ACCOUNTADMIN;

GRANT CREATE POSTGRES INSTANCE ON ACCOUNT TO i2b2;

USE ROLE i2b2;

use database i2b2_dev;
use schema public;
-- Create the ingress rule
CREATE OR REPLACE NETWORK RULE PG_INGRESS_MU_NETWORK
  TYPE = IPV4
  VALUE_LIST = ('161.130.0.0/16')
  MODE = POSTGRES_INGRESS;

CREATE OR REPLACE NETWORK RULE PG_INGRESS_I2B2_DEV_AWS_NETWORK
  TYPE = IPV4
  VALUE_LIST = ('3.22.45.33/32', '18.119.66.52/32')
  MODE = POSTGRES_INGRESS;


USE ROLE ACCOUNTADMIN;
-- Create a new policy using both rules in its allowed list
CREATE NETWORK POLICY "I2B2 PM DEV POLICY"
  ALLOWED_NETWORK_RULE_LIST = ('PG_INGRESS_MU_NETWORK', 'PG_INGRESS_I2B2_DEV_AWS_NETWORK')
  COMMENT = 'Traffic from the MU AND I2B2 DEV AWS.';

USE ROLE i2b2;
-- Create a new Snowflake Postgres instance that uses the new policy
CREATE POSTGRES INSTANCE SNOWFLAKE_POSTGRES_I2B2_DEV_PM
  COMPUTE_FAMILY = 'STANDARD_M'
  STORAGE_SIZE_GB = 50
  AUTHENTICATION_AUTHORITY = POSTGRES
  POSTGRES_VERSION = 18
  NETWORK_POLICY = '"I2B2 PM DEV POLICY"';

USE ROLE i2b2;
use database i2b2_prod;
use schema public;

CREATE OR REPLACE NETWORK RULE PG_INGRESS_I2B2_PROD_AWS_NETWORK
  TYPE = IPV4
  VALUE_LIST = ('18.189.169.253/32')
  MODE = POSTGRES_INGRESS;

CREATE OR REPLACE NETWORK RULE PG_INGRESS_MU_NETWORK
  TYPE = IPV4
  VALUE_LIST = ('161.130.0.0/16')
  MODE = POSTGRES_INGRESS;

USE ROLE accountadmin;
-- Create a new policy using both rules in its allowed list
CREATE NETWORK POLICY "I2B2 PM PROD POLICY"
  ALLOWED_NETWORK_RULE_LIST = ('PG_INGRESS_MU_NETWORK', 'PG_INGRESS_I2B2_PROD_AWS_NETWORK')
  COMMENT = 'Traffic from the MU AND I2B2 PROD AWS.';


-- Create a new Snowflake Postgres instance that uses the new policy
USE ROLE i2b2;

CREATE POSTGRES INSTANCE SNOWFLAKE_POSTGRES_I2B2_PROD_PM
  COMPUTE_FAMILY = 'STANDARD_M'
  STORAGE_SIZE_GB = 100
  AUTHENTICATION_AUTHORITY = POSTGRES
  POSTGRES_VERSION = 18
  NETWORK_POLICY = '"I2B2 PM PROD POLICY"';