BEGIN
    CREATE DATABASE IF NOT EXISTS I2B2_PCORNET_PROD;
    USE DATABASE I2B2_PCORNET_PROD;
    
    CREATE OR REPLACE SCHEMA I2B2DATA;
    CREATE OR REPLACE SCHEMA I2B2METADATA;
    CREATE OR REPLACE SCHEMA I2B2HIVE;
    CREATE OR REPLACE SCHEMA I2B2PM;
    CREATE OR REPLACE SCHEMA I2B2WORKDATA;
END;