USE ROLE ACCOUNTADMIN;

-- 1. Role ------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS I2B2_GPC;

-- 2. Warehouse -------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS I2B2_GPC_WH
    WAREHOUSE_SIZE      = 'LARGE'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = TRUE;
    
GRANT USAGE, OPERATE ON WAREHOUSE I2B2_GPC_WH TO ROLE I2B2_GPC;

-- 3. Database and the six i2b2 schemas -------------------------------------
CREATE DATABASE IF NOT EXISTS I2B2_GPC;
USE DATABASE I2B2_GPC;

CREATE SCHEMA IF NOT EXISTS I2B2METADATA_V183;   -- Metadata cell (ontology)
CREATE SCHEMA IF NOT EXISTS I2B2DATA_V183;       -- CRC / data mart cell


-- 4. Grants: full privileges on the database + current and future objects
--    so the installer can create tables, sequences, views, procedures and
--    load data into every schema.
GRANT ALL PRIVILEGES ON DATABASE  I2B2_GPC                 TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON ALL SCHEMAS    IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON ALL TABLES     IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON FUTURE TABLES  IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES    IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON ALL VIEWS      IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;
GRANT ALL PRIVILEGES ON FUTURE VIEWS   IN DATABASE I2B2_GPC TO ROLE I2B2_GPC;


CREATE USER IF NOT EXISTS I2B2_GPC_USER
    TYPE              = SERVICE
    RSA_PUBLIC_KEY    = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A...REPLACE_WITH_PUBLIC_KEY_BODY...'
    DEFAULT_ROLE      = I2B2_GPC
    DEFAULT_WAREHOUSE = I2B2_GPC_WH
    DEFAULT_NAMESPACE = I2B2_GPC
    COMMENT           = '';
GRANT ROLE I2B2_GPC TO USER I2B2_GPC_USER;

-- To rotate the key later:
--   ALTER USER I2B2 SET RSA_PUBLIC_KEY = '<new public key body>';
