use database CDM_DATALAKE;
use role i2b2;

CALL CDM_DATALAKE.PUBLIC.RUN_GPC_ETL_PROCESS(
        'DEIDENTIFIED_GROUSE_DB',
        'PCORNET_CDM_',
        'V_',
        'GPC_',
        'PCORNET_CDM_MU',
        'CDM_DATALAKE',
        'GPC',
        NULL   -- SITE_DATAMARTID_FILTER: NULL = all sites
    );

CALL CDM_DATALAKE.PUBLIC.RUN_GPC_ETL_PROCESS(
        'DEIDENTIFIED_GROUSE_DB',
        'PCORNET_CDM_',
        'V_',
        'GPC_',
        'PCORNET_CDM_MU',
        'CDM_DATALAKE',
        'WASHU',
        'C4WU' -- SITE_DATAMARTID_FILTER
    );    


CREATE OR REPLACE TABLE I2B2_SANDBOX_GPC.I2B2DATA.COVID_FACT AS
SELECT * FROM I2B2_SANDBOX_GPC.I2B2DATA.DIAGNOSIS_FACT
UNION ALL
SELECT * FROM I2B2_SANDBOX_GPC.I2B2DATA.PROCEDURE_FACT
UNION ALL
SELECT * FROM I2B2_SANDBOX_GPC.I2B2DATA.LAB_FACT
UNION ALL
SELECT * FROM I2B2_SANDBOX_GPC.I2B2DATA.MEDICATION_FACT
UNION ALL
SELECT * FROM I2B2_SANDBOX_GPC.I2B2DATA.VISIT_FACT
UNION ALL
SELECT * FROM I2B2_SANDBOX_GPC.I2B2DATA.DEMOGRAPHIC_FACT;


---Temp
drop table I2B2_SANDBOX_GPC.I2B2DATA.TUMOR_FACT;

update I2B2_SANDBOX_GPC.I2B2METADATA.TABLE_ACCESS
set c_visualattributes = 'FH' where c_table_cd = 'NAACCR_ONTOLOGY' ;
--- 
