GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA i2b2_dev.i2b2data TO ROLE i2b2_dev_app_role;
GRANT  ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA i2b2_dev.i2b2data TO ROLE i2b2_dev_app_role;


GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA i2b2_dev.i2b2data TO ROLE i2b2_dev_app_role;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA i2b2_dev.i2b2data TO ROLE i2b2_dev_app_role;


GRANT USAGE ON ALL SEQUENCES IN SCHEMA i2b2_dev.i2b2data TO ROLE i2b2_dev_app_role;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA i2b2_dev.i2b2data TO ROLE i2b2_dev_app_role;
