
select GISJOIN, FIPS, ADI_NATRANK, ADI_STATERNK from ACS.ADI.ADI_2021;


select PATID, MATCHED_STREET, MATCHED_ZIP, MATCHED_CITY, MATCHED_STATE, LAT, LON, SCORE, PRECISION, STREET1, STREET2, GEOCODE_RESULT
from GEO_CODING.DEGAUSS_TRANSFORMATION.DEID_GEOCODED_ADDRESS;

select PATID, ADDRESS, FIPS_BLOCK_GROUP_ID_2020, FIPS_TRACT_ID_2020
from PCORNET_CDM.CDM_2023_NOV.PRIVATE_GEOCODED_ADDRESS;

select g.patid, a.* from ACS.ADI.ADI_2021 a
left join PCORNET_CDM.CDM_2023_NOV.PRIVATE_GEOCODED_ADDRESS g
where (g.fips_block_group_id_2020) = to_varchar(a.fips);


 --GEOCODED ADDRESS Tables
select 
    PATID, ADDRESS, MATCHED_STREET, MATCHED_ZIP, MATCHED_CITY, MATCHED_STATE, LAT
    , LON, SCORE, PRECISION, STREET1, STREET2, GEOCODE_RESULT
from GEO_CODING.DEGAUSS_TRANSFORMATION.GEOCODED_ADDRESS;