#!/bin/bash
set -e
LOCAL_STAGE="file:///home/files"
SNOWFLAKE_STAGE="naaccr_ontology_import"
FILE_FORMAT="naaccr_ontology_import_format"
COPY_PARAMETERS=""
PUT_PARAMETERS="AUTO_COMPRESS=FALSE SOURCE_COMPRESSION=NONE OVERWRITE=TRUE"
# CONNECT TO SNOWFLAKE
snowsql -c etl_user <<- EOSQL

--- CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT $FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
EMPTY_FIELD_AS_NULL = true
TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
NULL_IF = ('NULL')
COMPRESSION=NONE
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1;

--- CREATE STAGE AREA
CREATE OR REPLACE STAGE $SNOWFLAKE_STAGE FILE_FORMAT = $FILE_FORMAT;

-- PUT LOCAL FILES INTO SNOWFLAKE STAGE
PUT $LOCAL_STAGE/* @$SNOWFLAKE_STAGE $PUT_PARAMETERS;


--- COPY ONTOLOGY TABLES FROM THE STAGE

CREATE OR REPLACE TABLE NAACCR_ONTOLOGY (
        C_HLEVEL                              INT    NOT NULL,
        C_FULLNAME                    VARCHAR(700)   NOT NULL,
        C_NAME                                VARCHAR(2000)  NOT NULL,
        C_SYNONYM_CD                  CHAR(1) NOT NULL,
        C_VISUALATTRIBUTES    CHAR(3) NOT NULL,
        C_TOTALNUM                    INT    NULL,
        C_BASECODE                    VARCHAR(50)    NULL,
        C_METADATAXML                 TEXT    NULL,
        C_FACTTABLECOLUMN             VARCHAR(50)    NOT NULL,
        C_TABLENAME                   VARCHAR(50)    NOT NULL,
        C_COLUMNNAME                  VARCHAR(50)    NOT NULL,
        C_COLUMNDATATYPE              VARCHAR(50)    NOT NULL,
        C_OPERATOR                    VARCHAR(10)    NOT NULL,
        C_DIMCODE                             VARCHAR(700)   NOT NULL,
        C_COMMENT                             TEXT    NULL,
        C_TOOLTIP                             VARCHAR(900)   NULL,
        M_APPLIED_PATH                VARCHAR(700)   NOT NULL,
        UPDATE_DATE                   DATE    NOT NULL,
        DOWNLOAD_DATE                 DATE    NULL,
        IMPORT_DATE                   DATE    NULL,
        SOURCESYSTEM_CD               VARCHAR(50)    NULL,
        VALUETYPE_CD                  VARCHAR(50)    NULL,
        M_EXCLUSION_CD                        VARCHAR(25) NULL,
        C_PATH                                VARCHAR(700)   NULL,
        C_SYMBOL                              VARCHAR(50)    NULL
)
;

COPY INTO NAACCR_ONTOLOGY from @$SNOWFLAKE_STAGE/naaccr_ontology.csv $COPY_PARAMETERS;


EOSQL
