use database I2B2_SANDBOX_VASANTHI;
use schema I2B2DATA;

CREATE OR REPLACE VIEW COVID_FACT as 
SELECT * FROM DIAGNOSIS_FACT 
UNION ALL
SELECT * FROM PROCEDURE_FACT
UNION ALL
SELECT * FROM LAB_FACT
UNION ALL 
SELECT * FROM PRESCRIBING_FACT;