SET database_name = 'i2b2_shrine_mu_prod';
SET schema_name = 'i2b2metadata';
SET source_schema = 'i2b2_etl_test.i2b2metadata';
SET target_schema = $database_name || '.' || $schema_name;
SET app_role = 'shrine_prod_mu_app_role';
SET role_tbl = $database_name || '.I2B2PM.PM_PROJECT_USER_ROLES';
SET user_tbl = $database_name || '.I2B2PM.PM_USER_DATA';
GRANT ALL PRIVILEGES ON DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT USAGE ON ALL SEQUENCES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($app_role);

DELETE FROM IDENTIFIER($role_tbl)
WHERE USER_ROLE_CD IN ('DATA_LDS', 'DATA_PROT');

INSERT INTO IDENTIFIER($role_tbl) (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
SELECT 'ACT', user_id, 'DATA_LDS', 'A' FROM IDENTIFIER($user_tbl);
CREATE OR REPLACE SCHEMA IDENTIFIER($target_schema) CLONE IDENTIFIER($source_schema);

create or replace TABLE I2B2_SHRINE_MU_PROD.I2B2DATA.CONCEPT_DIMENSION clone I2B2_SHRINE_MU_DEV.I2B2DATA.CONCEPT_DIMENSION;

create or replace TABLE I2B2_SHRINE_MU_PROD.I2B2DATA.QT_BREAKDOWN_PATH clone I2B2_SHRINE_MU_DEV.I2B2DATA.QT_BREAKDOWN_PATH;

create or replace TABLE I2B2_SHRINE_MU_PROD.I2B2DATA.QT_QUERY_RESULT_TYPE clone I2B2_SHRINE_MU_DEV.I2B2DATA.QT_QUERY_RESULT_TYPE;

create or replace TABLE I2B2_SHRINE_MU_PROD.I2B2DATA.QT_QUERY_STATUS_TYPE clone I2B2_SHRINE_MU_DEV.I2B2DATA.QT_QUERY_STATUS_TYPE;

-----
create or replace schema I2B2_SHRINE_WASHU_PROD.I2B2METADATA clone I2B2_SHRINE_WASHU_DEV.I2B2METADATA;

create or replace TABLE I2B2_SHRINE_WASHU_PROD.I2B2DATA.CONCEPT_DIMENSION clone I2B2_SHRINE_WASHU_DEV.I2B2DATA.CONCEPT_DIMENSION;

create or replace TABLE I2B2_SHRINE_WASHU_PROD.I2B2DATA.QT_BREAKDOWN_PATH clone I2B2_SHRINE_WASHU_DEV.I2B2DATA.QT_BREAKDOWN_PATH;

create or replace TABLE I2B2_SHRINE_WASHU_PROD.I2B2DATA.QT_QUERY_RESULT_TYPE clone I2B2_SHRINE_WASHU_DEV.I2B2DATA.QT_QUERY_RESULT_TYPE;

create or replace TABLE I2B2_SHRINE_WASHU_PROD.I2B2DATA.QT_QUERY_STATUS_TYPE clone I2B2_SHRINE_WASHU_DEV.I2B2DATA.QT_QUERY_STATUS_TYPE;

insert into i2b2_shrine_mu_prod.i2b2pm.pm_user_params (
    DATATYPE_CD, USER_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, STATUS_CD
)
select
    'T',
    user_id,
    'authentication_method',
    'SAML',
    CURRENT_DATE,
    CURRENT_DATE,
    'A'
from i2b2_shrine_mu_prod.i2b2pm.pm_user_data
where user_id  like '%@%.%';