
CREATE OR REPLACE TABLE I2B2_PROD.I2B2PM.PM_USER_DATA_BACKUP AS
SELECT *
FROM I2B2_PROD.I2B2PM.PM_USER_DATA;

CREATE OR REPLACE TABLE I2B2_PROD.I2B2PM.PM_USER_DATA_DEDUP AS
SELECT *
FROM I2B2_PROD.I2B2PM.PM_USER_DATA
WHERE status_cd = 'A'
  AND email <> 'testing@example.com'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY user_id
    ORDER BY entry_date DESC
) = 1;

truncate table I2B2_PROD.I2B2PM.PM_USER_DATA;

insert into I2B2_PROD.I2B2PM.PM_USER_DATA
select * from I2B2_PROD.I2B2PM.PM_USER_DATA_DEDUP;

CREATE OR REPLACE TABLE I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES_BACKUP AS
SELECT *
FROM I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES;

CREATE OR REPLACE TABLE I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES_DEDUP AS
SELECT *
FROM I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY project_id, user_id, user_role_cd
    ORDER BY change_date DESC
) = 1;

truncate table I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES;
insert into I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES
select * from I2B2_PROD.I2B2PM.PM_PROJECT_USER_ROLES_DEDUP;


truncate i2b2_prod.i2b2pm.pm_user_params;

insert into i2b2_prod.i2b2pm.pm_user_params(DATATYPE_CD, USER_ID, PARAM_NAME_CD, VALUE, STATUS_CD)
select distinct
'T'
, user_id
, 'authentication_method'
, 'SAML'
, 'A'
from i2b2_prod.i2b2pm.pm_user_data
where user_id <> 'AGG_SERVICE_ACCOUNT';