create or replace database I2B2_PROD;
use database I2B2_PROD;
create schema i2b2data;
create schema i2b2hive;
create schema i2b2metadata;
create schema i2b2pm;
create schema i2b2workdata;


-- fact tables
create or replace table I2B2DATA.OBSERVATION_FACT like I2B2_DEV.I2B2DATA.OBSERVATION_FACT;
create or replace table I2B2DATA.DEMOGRAPHIC_FACT like I2B2DATA.DEMOGRAPHIC_FACT;
create or replace table I2B2DATA.DIAGNOSIS_FACT like I2B2_DEV.I2B2DATA.DIAGNOSIS_FACT;
create or replace table I2B2DATA.LAB_FACT like I2B2_DEV.I2B2DATA.LAB_FACT;
create or replace table I2B2DATA.PRESCRIBING_FACT like I2B2_DEV.I2B2DATA.PRESCRIBING_FACT;
create or replace table I2B2DATA.PROCEDURE_FACT like I2B2_DEV.I2B2DATA.PROCEDURE_FACT;
create or replace table I2B2DATA.VITAL_FACT like I2B2_DEV.I2B2DATA.VITAL_FACT;
create or replace table I2B2DATA.VISIT_FACT like I2B2_DEV.I2B2DATA.VISIT_FACT;
create or replace table I2B2DATA.OBSCLIN_FACT like I2B2_DEV.I2B2DATA.OBSCLIN_FACT;


insert into I2B2DATA.LAB_FACT(select * from I2B2_DEV.I2B2DATA.LAB_FACT);
insert into I2B2DATA.OBSERVATION_FACT (select * from I2B2_DEV.I2B2DATA.OBSERVATION_FACT);
insert into I2B2DATA.PRESCRIBING_FACT (select * from I2B2_DEV.I2B2DATA.PRESCRIBING_FACT);
insert into I2B2DATA.PROCEDURE_FACT (select * from I2B2_DEV.I2B2DATA.PROCEDURE_FACT);
insert into I2B2DATA.DIAGNOSIS_FACT (select * from I2B2_DEV.I2B2DATA.DIAGNOSIS_FACT);
insert into I2B2DATA.DEMOGRAPHIC_FACT (select * from I2B2_DEV.I2B2DATA.DEMOGRAPHIC_FACT);
insert into I2B2DATA.VITAL_FACT (select * from I2B2_DEV.I2B2DATA.VITAL_FACT);
insert into I2B2DATA.VISIT_FACT (select * from I2B2_DEV.I2B2DATA.VISIT_FACT);
insert into I2B2DATA.OBSCLIN_FACT (select * from I2B2_DEV.I2B2DATA.OBSCLIN_FACT);

-- dimension tables
create or replace table I2B2DATA.CONCEPT_DIMENSION like I2B2_DEV.I2B2DATA.CONCEPT_DIMENSION;
create or replace table I2B2DATA.MODIFIER_DIMENSION like I2B2_DEV.I2B2DATA.MODIFIER_DIMENSION;
create or replace table I2B2DATA.PATIENT_DIMENSION like I2B2_DEV.I2B2DATA.PATIENT_DIMENSION;
create or replace table I2B2DATA.PROVIDER_DIMENSION like I2B2_DEV.I2B2DATA.PROVIDER_DIMENSION;
create or replace table I2B2DATA.VISIT_DIMENSION like I2B2_DEV.I2B2DATA.VISIT_DIMENSION;

insert into I2B2DATA.PROVIDER_DIMENSION (select * from I2B2_DEV.I2B2DATA.PROVIDER_DIMENSION);
insert into I2B2DATA.VISIT_DIMENSION (select * from I2B2_DEV.I2B2DATA.VISIT_DIMENSION);
insert into I2B2DATA.PATIENT_DIMENSION (select * from I2B2_DEV.I2B2DATA.PATIENT_DIMENSION);
insert into I2B2DATA.MODIFIER_DIMENSION (select * from I2B2_DEV.I2B2DATA.MODIFIER_DIMENSION);
insert into I2B2DATA.CONCEPT_DIMENSION (select * from I2B2_DEV.I2B2DATA.CONCEPT_DIMENSION);


-- mapping tables
create or replace table I2B2DATA.CODE_LOOKUP like I2B2_DEV.I2B2DATA.CODE_LOOKUP;
create or replace table I2B2DATA.DATAMART_REPORT like I2B2_DEV.I2B2DATA.DATAMART_REPORT;
create or replace table I2B2DATA.ENCOUNTER_MAPPING like I2B2_DEV.I2B2DATA.ENCOUNTER_MAPPING;
create or replace table I2B2DATA.PATIENT_MAPPING like I2B2_DEV.I2B2DATA.PATIENT_MAPPING;

insert into I2B2DATA.CODE_LOOKUP (select * from I2B2_DEV.I2B2DATA.CODE_LOOKUP);
insert into I2B2DATA.DATAMART_REPORT (select * from I2B2_DEV.I2B2DATA.DATAMART_REPORT);
insert into I2B2DATA.ENCOUNTER_MAPPING (select * from I2B2_DEV.I2B2DATA.ENCOUNTER_MAPPING);
insert into I2B2DATA.PATIENT_MAPPING (select * from I2B2_DEV.I2B2DATA.PATIENT_MAPPING);

-- qt tables
create or replace table I2B2DATA.QT_ANALYSIS_PLUGIN like I2B2_DEV.I2B2DATA.QT_ANALYSIS_PLUGIN;
create or replace table I2B2DATA.QT_ANALYSIS_PLUGIN_RESULT_TYPE like I2B2_DEV.I2B2DATA.QT_ANALYSIS_PLUGIN_RESULT_TYPE;
create or replace table I2B2DATA.QT_BREAKDOWN_PATH like I2B2_DEV.I2B2DATA.QT_BREAKDOWN_PATH;
create or replace table I2B2DATA.QT_PATIENT_ENC_COLLECTION like I2B2_DEV.I2B2DATA.QT_PATIENT_ENC_COLLECTION;
create or replace table I2B2DATA.QT_PATIENT_SET_COLLECTION like I2B2_DEV.I2B2DATA.QT_PATIENT_SET_COLLECTION;
create or replace table I2B2DATA.QT_PDO_QUERY_MASTER like I2B2_DEV.I2B2DATA.QT_PDO_QUERY_MASTER;
create or replace table I2B2DATA.QT_PRIVILEGE like I2B2_DEV.I2B2DATA.QT_PRIVILEGE;
create or replace table I2B2DATA.QT_QUERY_INSTANCE like I2B2_DEV.I2B2DATA.QT_QUERY_INSTANCE;
create or replace table I2B2DATA.QT_QUERY_MASTER like I2B2_DEV.I2B2DATA.QT_QUERY_MASTER;
create or replace table I2B2DATA.QT_QUERY_RESULT_INSTANCE like I2B2_DEV.I2B2DATA.QT_QUERY_RESULT_INSTANCE;
create or replace table I2B2DATA.QT_QUERY_RESULT_TYPE like I2B2_DEV.I2B2DATA.QT_QUERY_RESULT_TYPE;
create or replace table I2B2DATA.QT_QUERY_STATUS_TYPE like I2B2_DEV.I2B2DATA.QT_QUERY_STATUS_TYPE;
create or replace table I2B2DATA.QT_XML_RESULT like I2B2_DEV.I2B2DATA.QT_XML_RESULT;
create or replace table I2B2DATA.SET_TYPE like I2B2_DEV.I2B2DATA.SET_TYPE;
create or replace table I2B2DATA.SET_UPLOAD_STATUS like I2B2_DEV.I2B2DATA.SET_UPLOAD_STATUS;
create or replace table I2B2DATA.SOURCE_MASTER like I2B2_DEV.I2B2DATA.SOURCE_MASTER;
create or replace table I2B2DATA.UPLOAD_STATUS like I2B2_DEV.I2B2DATA.UPLOAD_STATUS;

insert into I2B2DATA.QT_ANALYSIS_PLUGIN (select * from I2B2_DEV.I2B2DATA.QT_ANALYSIS_PLUGIN);
insert into I2B2DATA.QT_ANALYSIS_PLUGIN_RESULT_TYPE (select * from I2B2_DEV.I2B2DATA.QT_ANALYSIS_PLUGIN_RESULT_TYPE);
insert into I2B2DATA.QT_BREAKDOWN_PATH (select * from I2B2_DEV.I2B2DATA.QT_BREAKDOWN_PATH);
insert into I2B2DATA.QT_PATIENT_ENC_COLLECTION (select * from I2B2_DEV.I2B2DATA.QT_PATIENT_ENC_COLLECTION);
insert into I2B2DATA.QT_PATIENT_SET_COLLECTION (select * from I2B2_DEV.I2B2DATA.QT_PATIENT_SET_COLLECTION);
insert into I2B2DATA.QT_PDO_QUERY_MASTER (select * from I2B2_DEV.I2B2DATA.QT_PDO_QUERY_MASTER);
insert into I2B2DATA.QT_PRIVILEGE (select * from I2B2_DEV.I2B2DATA.QT_PRIVILEGE);
insert into I2B2DATA.QT_QUERY_INSTANCE (select * from I2B2_DEV.I2B2DATA.QT_QUERY_INSTANCE);
insert into I2B2DATA.QT_QUERY_MASTER (select * from I2B2_DEV.I2B2DATA.QT_QUERY_MASTER);
insert into I2B2DATA.QT_QUERY_RESULT_INSTANCE (select * from I2B2_DEV.I2B2DATA.QT_QUERY_RESULT_INSTANCE);
insert into I2B2DATA.QT_QUERY_RESULT_TYPE (select * from I2B2_DEV.I2B2DATA.QT_QUERY_RESULT_TYPE);
insert into I2B2DATA.QT_QUERY_STATUS_TYPE (select * from I2B2_DEV.I2B2DATA.QT_QUERY_STATUS_TYPE);
insert into I2B2DATA.QT_XML_RESULT (select * from I2B2_DEV.I2B2DATA.QT_XML_RESULT);
insert into I2B2DATA.SET_TYPE (select * from I2B2_DEV.I2B2DATA.SET_TYPE);
insert into I2B2DATA.SET_UPLOAD_STATUS (select * from I2B2_DEV.I2B2DATA.SET_UPLOAD_STATUS);
insert into I2B2DATA.SOURCE_MASTER (select * from I2B2_DEV.I2B2DATA.SOURCE_MASTER);
insert into I2B2DATA.UPLOAD_STATUS (select * from I2B2_DEV.I2B2DATA.UPLOAD_STATUS);


-- HIVE


create or replace table I2B2HIVE.CRC_ANALYSIS_JOB like I2B2_DEV.I2B2HIVE.CRC_ANALYSIS_JOB;
create or replace table I2B2HIVE.CRC_DB_LOOKUP like I2B2_DEV.I2B2HIVE.CRC_DB_LOOKUP;
create or replace table I2B2HIVE.HIVE_CELL_PARAMS like I2B2_DEV.I2B2HIVE.HIVE_CELL_PARAMS;
create or replace table I2B2HIVE.IM_DB_LOOKUP like I2B2_DEV.I2B2HIVE.IM_DB_LOOKUP;
create or replace table I2B2HIVE.ONT_DB_LOOKUP like I2B2_DEV.I2B2HIVE.ONT_DB_LOOKUP;
create or replace table I2B2HIVE.WORK_DB_LOOKUP like I2B2_DEV.I2B2HIVE.WORK_DB_LOOKUP;


insert into I2B2HIVE.CRC_ANALYSIS_JOB (select * from I2B2_DEV.I2B2HIVE.CRC_ANALYSIS_JOB);
insert into I2B2HIVE.CRC_DB_LOOKUP (select * from I2B2_DEV.I2B2HIVE.CRC_DB_LOOKUP);
insert into I2B2HIVE.HIVE_CELL_PARAMS (select * from I2B2_DEV.I2B2HIVE.HIVE_CELL_PARAMS);
insert into I2B2HIVE.IM_DB_LOOKUP (select * from I2B2_DEV.I2B2HIVE.IM_DB_LOOKUP);
insert into I2B2HIVE.ONT_DB_LOOKUP (select * from I2B2_DEV.I2B2HIVE.ONT_DB_LOOKUP);
insert into I2B2HIVE.WORK_DB_LOOKUP (select * from I2B2_DEV.I2B2HIVE.WORK_DB_LOOKUP);


-- METADATA
create or replace table I2B2METADATA.ACT_COVID_V4 like I2B2_DEV.I2B2METADATA.ACT_COVID_V4;
create or replace table I2B2METADATA.ACT_CPT4_PX_V4 like I2B2_DEV.I2B2METADATA.ACT_CPT4_PX_V4;
create or replace table I2B2METADATA.ACT_DEM_V4 like I2B2_DEV.I2B2METADATA.ACT_DEM_V4;
create or replace table I2B2METADATA.ACT_HCPCS_PX_V4 like I2B2_DEV.I2B2METADATA.ACT_HCPCS_PX_V4;
create or replace table I2B2METADATA.ACT_ICD10CM_DX_V4 like I2B2_DEV.I2B2METADATA.ACT_ICD10CM_DX_V4;
create or replace table I2B2METADATA.ACT_ICD10PCS_PX_V4 like I2B2_DEV.I2B2METADATA.ACT_ICD10PCS_PX_V4;
create or replace table I2B2METADATA.ACT_ICD10_ICD9_DX_V4 like I2B2_DEV.I2B2METADATA.ACT_ICD10_ICD9_DX_V4;
create or replace table I2B2METADATA.ACT_ICD9CM_DX_V4 like I2B2_DEV.I2B2METADATA.ACT_ICD9CM_DX_V4;
create or replace table I2B2METADATA.ACT_ICD9CM_PX_V4 like I2B2_DEV.I2B2METADATA.ACT_ICD9CM_PX_V4;
create or replace table I2B2METADATA.ACT_LOINC_LAB_PROV_V4 like I2B2_DEV.I2B2METADATA.ACT_LOINC_LAB_PROV_V4;
create or replace table I2B2METADATA.ACT_LOINC_LAB_V4 like I2B2_DEV.I2B2METADATA.ACT_LOINC_LAB_V4;
create or replace table I2B2METADATA.ACT_MED_ALPHA_V4 like I2B2_DEV.I2B2METADATA.ACT_MED_ALPHA_V4;
create or replace table I2B2METADATA.ACT_MED_VA_V4 like I2B2_DEV.I2B2METADATA.ACT_MED_VA_V4;
create or replace table I2B2METADATA.ACT_SDOH_V4 like I2B2_DEV.I2B2METADATA.ACT_SDOH_V4;
create or replace table I2B2METADATA.ACT_VISIT_DETAILS_V4 like I2B2_DEV.I2B2METADATA.ACT_VISIT_DETAILS_V4;
create or replace table I2B2METADATA.ACT_VITAL_SIGNS_V4 like I2B2_DEV.I2B2METADATA.ACT_VITAL_SIGNS_V4;
create or replace table I2B2METADATA.ONT_PROCESS_STATUS like I2B2_DEV.I2B2METADATA.ONT_PROCESS_STATUS;
create or replace table I2B2METADATA.SCHEMES like I2B2_DEV.I2B2METADATA.SCHEMES;
create or replace table I2B2METADATA.TABLE_ACCESS like I2B2_DEV.I2B2METADATA.TABLE_ACCESS;
create or replace table I2B2METADATA.TOTALNUM like I2B2_DEV.I2B2METADATA.TOTALNUM;
create or replace table I2B2METADATA.TOTALNUM_REPORT like I2B2_DEV.I2B2METADATA.TOTALNUM_REPORT;
create or replace table I2B2METADATA.ACT_LOINC_OBSCLIN_V4 like I2B2_DEV.I2B2METADATA.ACT_LOINC_OBSCLIN_V4;


insert into I2B2METADATA.ACT_COVID_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_COVID_V4);
insert into I2B2METADATA.ACT_CPT4_PX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_CPT4_PX_V4);
insert into I2B2METADATA.ACT_DEM_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_DEM_V4);
insert into I2B2METADATA.ACT_HCPCS_PX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_HCPCS_PX_V4);
insert into I2B2METADATA.ACT_ICD10CM_DX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_ICD10CM_DX_V4);
insert into I2B2METADATA.ACT_ICD10PCS_PX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_ICD10PCS_PX_V4);
insert into I2B2METADATA.ACT_ICD10_ICD9_DX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_ICD10_ICD9_DX_V4);
insert into I2B2METADATA.ACT_ICD9CM_DX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_ICD9CM_DX_V4);
insert into I2B2METADATA.ACT_ICD9CM_PX_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_ICD9CM_PX_V4);
insert into I2B2METADATA.ACT_LOINC_LAB_PROV_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_LOINC_LAB_PROV_V4);
insert into I2B2METADATA.ACT_LOINC_LAB_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_LOINC_LAB_V4);
insert into I2B2METADATA.ACT_MED_ALPHA_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_MED_ALPHA_V4);
insert into I2B2METADATA.ACT_MED_VA_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_MED_VA_V4);
insert into I2B2METADATA.ACT_SDOH_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_SDOH_V4);
insert into I2B2METADATA.ACT_VISIT_DETAILS_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_VISIT_DETAILS_V4);
insert into I2B2METADATA.ACT_VITAL_SIGNS_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_VITAL_SIGNS_V4);
insert into I2B2METADATA.ONT_PROCESS_STATUS (select * from I2B2_DEV.I2B2METADATA.ONT_PROCESS_STATUS);
insert into I2B2METADATA.SCHEMES (select * from I2B2_DEV.I2B2METADATA.SCHEMES);
insert into I2B2METADATA.TABLE_ACCESS (select * from I2B2_DEV.I2B2METADATA.TABLE_ACCESS);
insert into I2B2METADATA.TOTALNUM (select * from I2B2_DEV.I2B2METADATA.TOTALNUM);
insert into I2B2METADATA.TOTALNUM_REPORT (select * from I2B2_DEV.I2B2METADATA.TOTALNUM_REPORT);
insert into I2B2METADATA.ACT_LOINC_OBSCLIN_V4 (select * from I2B2_DEV.I2B2METADATA.ACT_LOINC_OBSCLIN_V4);

-- PM
create or replace table I2B2PM.PM_APPROVALS like I2B2_DEV.I2B2PM.PM_APPROVALS;
create or replace table I2B2PM.PM_APPROVALS_PARAMS like I2B2_DEV.I2B2PM.PM_APPROVALS_PARAMS;
create or replace table I2B2PM.PM_CELL_DATA like I2B2_DEV.I2B2PM.PM_CELL_DATA;
create or replace table I2B2PM.PM_CELL_PARAMS like I2B2_DEV.I2B2PM.PM_CELL_PARAMS;
create or replace table I2B2PM.PM_GLOBAL_PARAMS like I2B2_DEV.I2B2PM.PM_GLOBAL_PARAMS;
create or replace table I2B2PM.PM_HIVE_DATA like I2B2_DEV.I2B2PM.PM_HIVE_DATA;
create or replace table I2B2PM.PM_HIVE_PARAMS like I2B2_DEV.I2B2PM.PM_HIVE_PARAMS;
create or replace table I2B2PM.PM_PROJECT_DATA like I2B2_DEV.I2B2PM.PM_PROJECT_DATA;
create or replace table I2B2PM.PM_PROJECT_PARAMS like I2B2_DEV.I2B2PM.PM_PROJECT_PARAMS;
create or replace table I2B2PM.PM_PROJECT_REQUEST like I2B2_DEV.I2B2PM.PM_PROJECT_REQUEST;
create or replace table I2B2PM.PM_PROJECT_USER_PARAMS like I2B2_DEV.I2B2PM.PM_PROJECT_USER_PARAMS;
create or replace table I2B2PM.PM_PROJECT_USER_ROLES like I2B2_DEV.I2B2PM.PM_PROJECT_USER_ROLES;
create or replace table I2B2PM.PM_ROLE_REQUIREMENT like I2B2_DEV.I2B2PM.PM_ROLE_REQUIREMENT;
create or replace table I2B2PM.PM_USER_DATA like I2B2_DEV.I2B2PM.PM_USER_DATA;
create or replace table I2B2PM.PM_USER_LOGIN like I2B2_DEV.I2B2PM.PM_USER_LOGIN;
create or replace table I2B2PM.PM_USER_PARAMS like I2B2_DEV.I2B2PM.PM_USER_PARAMS;
create or replace table I2B2PM.PM_USER_SESSION like I2B2_DEV.I2B2PM.PM_USER_SESSION;

insert into I2B2PM.PM_APPROVALS (select * from I2B2_DEV.I2B2PM.PM_APPROVALS);
insert into I2B2PM.PM_APPROVALS_PARAMS (select * from I2B2_DEV.I2B2PM.PM_APPROVALS_PARAMS);
insert into I2B2PM.PM_CELL_DATA (select * from I2B2_DEV.I2B2PM.PM_CELL_DATA);
insert into I2B2PM.PM_CELL_PARAMS (select * from I2B2_DEV.I2B2PM.PM_CELL_PARAMS);
insert into I2B2PM.PM_GLOBAL_PARAMS (select * from I2B2_DEV.I2B2PM.PM_GLOBAL_PARAMS);
insert into I2B2PM.PM_HIVE_DATA (select * from I2B2_DEV.I2B2PM.PM_HIVE_DATA);
insert into I2B2PM.PM_HIVE_PARAMS (select * from I2B2_DEV.I2B2PM.PM_HIVE_PARAMS);
insert into I2B2PM.PM_PROJECT_DATA (select * from I2B2_DEV.I2B2PM.PM_PROJECT_DATA);
insert into I2B2PM.PM_PROJECT_PARAMS (select * from I2B2_DEV.I2B2PM.PM_PROJECT_PARAMS);
insert into I2B2PM.PM_PROJECT_REQUEST (select * from I2B2_DEV.I2B2PM.PM_PROJECT_REQUEST);
insert into I2B2PM.PM_PROJECT_USER_PARAMS (select * from I2B2_DEV.I2B2PM.PM_PROJECT_USER_PARAMS);
insert into I2B2PM.PM_PROJECT_USER_ROLES (select * from I2B2_DEV.I2B2PM.PM_PROJECT_USER_ROLES);
insert into I2B2PM.PM_ROLE_REQUIREMENT (select * from I2B2_DEV.I2B2PM.PM_ROLE_REQUIREMENT);
insert into I2B2PM.PM_USER_DATA (select * from I2B2_DEV.I2B2PM.PM_USER_DATA);
insert into I2B2PM.PM_USER_LOGIN (select * from I2B2_DEV.I2B2PM.PM_USER_LOGIN);
insert into I2B2PM.PM_USER_PARAMS (select * from I2B2_DEV.I2B2PM.PM_USER_PARAMS);
insert into I2B2PM.PM_USER_SESSION (select * from I2B2_DEV.I2B2PM.PM_USER_SESSION);

--WORK
create or replace table I2B2WORKDATA.WORKPLACE like I2B2_DEV.I2B2WORKDATA.WORKPLACE;
create or replace table I2B2WORKDATA.WORKPLACE_ACCESS like I2B2_DEV.I2B2WORKDATA.WORKPLACE_ACCESS;

insert into I2B2WORKDATA.WORKPLACE (select * from I2B2_DEV.I2B2WORKDATA.WORKPLACE);
insert into I2B2WORKDATA.WORKPLACE_ACCESS (select * from I2B2_DEV.I2B2WORKDATA.WORKPLACE_ACCESS);
