USE DATABASE {target_db};
CREATE OR REPLACE SCHEMA {crc_schema};
CREATE OR REPLACE SCHEMA {hive_schema};
CREATE OR REPLACE SCHEMA {metadata_schema};
CREATE OR REPLACE SCHEMA {pm_schema};
CREATE OR REPLACE SCHEMA {wd_schema};